//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ViewStrings", typeof(ViewStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif.
        /// </summary>
        public static string Aktif {
            get {
                return ResourceManager.GetString("Aktif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bay.
        /// </summary>
        public static string Bay {
            get {
                return ResourceManager.GetString("Bay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayan.
        /// </summary>
        public static string Bayan {
            get {
                return ResourceManager.GetString("Bayan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim alanı zorunludur..
        /// </summary>
        public static string BirimHatasi {
            get {
                return ResourceManager.GetString("BirimHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string CustomerEmail {
            get {
                return ResourceManager.GetString("CustomerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Id.
        /// </summary>
        public static string CustomerId {
            get {
                return ResourceManager.GetString("CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string CustomerPhone {
            get {
                return ResourceManager.GetString("CustomerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet.
        /// </summary>
        public static string Evet {
            get {
                return ResourceManager.GetString("Evet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır.
        /// </summary>
        public static string Hayir {
            get {
                return ResourceManager.GetString("Hayir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlemler.
        /// </summary>
        public static string Islemler {
            get {
                return ResourceManager.GetString("Islemler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST : A {0} component was created..
        /// </summary>
        public static string LogForCreate {
            get {
                return ResourceManager.GetString("LogForCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE : {0} component with id: {1}  was deleted..
        /// </summary>
        public static string LogForDelete {
            get {
                return ResourceManager.GetString("LogForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET : {0} component with id: {1}  was received..
        /// </summary>
        public static string LogForGet {
            get {
                return ResourceManager.GetString("LogForGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GETALL : All {0} were received..
        /// </summary>
        public static string LogForGetAll {
            get {
                return ResourceManager.GetString("LogForGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE : {0} component with id: {1}  was not deleted..
        /// </summary>
        public static string LogForNotDelete {
            get {
                return ResourceManager.GetString("LogForNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET ERROR : {0} component with id: {1}  was not received..
        /// </summary>
        public static string LogForNotGet {
            get {
                return ResourceManager.GetString("LogForNotGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATCH ERROR: {0} component with  id: {1} was updated..
        /// </summary>
        public static string LogForNotUpdate {
            get {
                return ResourceManager.GetString("LogForNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATCH : {0} component with  id: {1} was updated..
        /// </summary>
        public static string LogForUpdate {
            get {
                return ResourceManager.GetString("LogForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Seçiniz.
        /// </summary>
        public static string LutfenSeciniz {
            get {
                return ResourceManager.GetString("LutfenSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasif.
        /// </summary>
        public static string Pasif {
            get {
                return ResourceManager.GetString("Pasif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Amount.
        /// </summary>
        public static string ProductAmount {
            get {
                return ResourceManager.GetString("ProductAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Id.
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
    }
}
